language: node_js
node_js:
  - "7"

cache:
  yarn: true

script:
    - npm run build

deploy:
  local_dir: public
  provider: pages
  skip_cleanup: true
  github_token: $token
  on:
    branch: master
  target_branch: gh-pages
