language: node_js
node_js:
- "node"

before_script:
- npm test

script:
- npm run build

deploy:
  local_dir: public
  provider: pages
  skip_cleanup: true
  github_token: $token
  on:
    branch: master
  target_branch: gh-pages
